version: "3"

services:
  redis:
    container_name: redis
    image: bitnami/redis:6.0 # same image as https://docs.railway.app/databases/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
